trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: - script: dotnet restore src/CustomFFTConsoleApp/CustomFFTConsoleApp.csproj
  displayName: Restore Packages

- script: - script: dotnet build src/CustomFFTConsoleApp/CustomFFTConsoleApp.csproj --configuration Release
  displayName: Build Application

- script: dotnet publish src/CustomFFTConsoleApp -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: Publish Application

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'custom-fft-app'